server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/table-booking?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  publicKey: classpath:public-key.pem
  privateKey: classpath:pkcs8.key